Alfredo/Models/Computer.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.NetworkInformation;
using System.Security.Cryptography;
using System.Text;

namespace Alfredo.Models
{
    public enum PingStatus { Running, NoReply, Unknown}
    public class Computer
    {
        public readonly int Id;

        [Required]
        public string Name { get; set; }
        public IPAddress? IP { get; set; }
        public string[]? MAC { get; set; }
        public IPStatus Status { get; set; }
        //TODO Aggiungere una firma temporale LastTimeCheck
        public Computer() 
        {            
        }

        public Computer(string name, string ip, string mac)
        {
            this.Name = name;
            SetIP(ip);
            SetMAC(mac);
            Status = IPStatus.Unknown;

            string[] charArray = ip.Split('.');
            string extIp = string.Join(null,charArray);
            Id = Int32.Parse(extIp);
        }

        public void SetIP(string ip) => IP = IPAddress.Parse(ip);

        public void SetMAC(string mac)
        {
            string[] macDigits = null;
            if (mac.Contains("-"))
                macDigits = mac.Split('-');
            else
                macDigits = mac.Split(':');

            if (macDigits.Length != 6)
                throw new ArgumentException("Incorrect MAC address format");

            MAC = macDigits;
        }

        public string GetMAC()
        {
            return string.Join(':', MAC);
        }
    }
}

Alfredo/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;

namespace Alfredo.Models
{
    public enum PizzaSize { Small, Medium, Large }

    public class Pizza
    {
        public int Id { get; set; }

        [Required] //attributo per indicare che i campi nel form html devono essere richiesti
        public string? Name { get; set; }
        public PizzaSize Size { get; set; }
        public bool IsGlutenFree { get; set; }

        [Range(0.01, 9999.99)]
        public decimal Price { get; set; }
    }
}

Alfredo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Alfredo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Alfredo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Alfredo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Alfredo/Pages/Network.cshtml.cs
using Alfredo.Models;
using Alfredo.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Alfredo.Pages
{
    public class NetworkModel : PageModel
    {
        WOLService service = new WOLService();

        [BindProperty]
        public Computer NewComputer { get; set; } = new();
        public List<Computer> Computers = new();
        
        public string ConnectionStatusText(Computer computer)
        {
            return computer.Status.ToString();
        }
        public void OnGet()
        {
            Computers = service.GetAll();
        }

        public IActionResult OnPostAsync() 
        {
            if (!ModelState.IsValid)
                return Page();
            service.Add(NewComputer);
            return RedirectToAction("Get"); 
        }
        public IActionResult OnPostDelete(int id)
        {
            service.Delete(id);
            return RedirectToAction("Get");
        }
        public IActionResult OnPostCheckStatus(int id) 
        {
            service.UpdateStatus(id);
            return RedirectToAction("Get");
        }
        public IActionResult OnPostCheckStatusForAll(int id)
        {
            service.UpdateStatusForAll();
            return RedirectToAction("Get");
        }
        public IActionResult OnPostWake(int id)
        {
            service.Wake(id);
            return RedirectToAction("Get");
        }

    }
}

Alfredo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Alfredo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Alfredo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcomeeeeee</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>Sono Alfredo, solo che ancora non posso fare niente :( Pero' se vuoi puoi ordinare una pizza nel menù qui accanto ;)'</p>
</div>

Alfredo/Pages/Network.cshtml
@page
@using Alfredo.Models
@model Alfredo.Pages.NetworkModel
@{
    ViewData["Title"] = "Devices List";
}

<h1>Devices List</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-1 align-middle">
        <label asp-for="NewComputer.Name">Name</label>
        @*il tag asp-for va a connettersi ad un oggetto del model, in particolare NewPizza*@
        <input type="text" asp-for="NewComputer.Name" class="mr-6" />
        <label asp-for="NewComputer.IP">Ip Address</label>
        <input type="text" asp-for="NewComputer.IP" class="mr-6" />
        <label asp-for="NewComputer.MAC">Mac Address</label>
        <input type="text" asp-for="NewComputer.MAC" class="mr-6" />
        <button class="btn btn-primary">Add</button>
    </div>
</form>

<div class="refresh-btn align-content-md-center">
    
    <form method="post" asp-page-handler="CheckStatusForAll">
        <button class="refresh-btn btn-primary">Check Status</button>
    </form>
</div>

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">IP</th>
            <th scope="col">MAC</th>
            <th scope="col">Status</th>
            <th scope="col">UpdateStatus</th>
            <th scope="col">Wake</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    @foreach (var dev in Model.Computers)
    {
        <tr>
            <td>@dev.Id</td>
            <td>@dev.Name</td>
            <td>@dev.IP</td>
            <td>@dev.GetMAC()</td>
            <td>@Model.ConnectionStatusText(dev)</td>           
            <td>
                <form method="post" asp-page-handler="CheckStatus" asp-route-id="@dev.Id">
                    <button class="btn btn-secondary">CheckStatus</button>
                </form>
            </td>
            <td>
                <form method="post" asp-page-handler="Wake" asp-route-id="@dev.Id">
                    <button class="btn btn-secondary">Wake</button>
                </form>
            </td>
            <td>
                <form method="post" asp-page-handler="Delete" asp-route-id="@dev.Id">
                    <button class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Alfredo/Pages/Pizza.cshtml
@page
@using Alfredo.Models
@model Alfredo.Pages.PizzaModel
@{
    ViewData["Title"] = "Pizzas List";
}

<h1>Pizza List</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <label asp-for="NewPizza.Name">Name</label>
        @*il tag asp-for va a connettersi ad un oggetto del model, in particolare NewPizza*@
        <input type="text" asp-for="NewPizza.Name" class="mr-5" />
        <label asp-for="NewPizza.Size">Size</label>
        <select asp-for="NewPizza.Size" asp-items="Html.GetEnumSelectList<PizzaSize>()" class="mr-5"></select>
        <label asp-for="NewPizza.Price">Price</label>
        <input asp-for="NewPizza.Price" class="mr-5" />
        <label asp-for="NewPizza.IsGlutenFree">IsGlutenFree</label>
        <input type="checkbox" asp-for="NewPizza.IsGlutenFree" class="mr-5" />
        <button class="btn btn-primary">Add</button>
    </div>
</form>
<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Size</th>
            <th scope="col">Gluten Free</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    @foreach (var pizza in Model.Pizzas)
    {
        <tr>
            <td>@pizza.Name</td>
            <td>@($"{pizza.Price:C}")</td>
            <td>@pizza.Size</td>
            <td>@Model.GlutenFreeText(pizza)</td>
            <td>
                <form method="post" asp-page-handler="Delette" asp-route-id="@pizza.Id">
                    <button class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

Alfredo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alfredo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Alfredo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Alfredo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Pizza">Pizza</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Network">Network</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Alfredo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>